### ISSUE TITLE
BoF Call for Paper案内

### ISSUE THREAD

**Issue by mshindo** [onicjapan/onicjapan.github.io#10]
BoFのCall for Paperの告知を記事として投稿。

**Comment by canaan** [comment]
Push してみました〜

**Comment by canaan** [comment]
クリック力が足りてなかったようです。今、commit -> push しました。githubのページにも反映されてます〜

**Comment by mshindo** [comment]
addressed with da5b75cb459f6667457751dc6af4aca567815506, closing this issue.
