### ISSUE TITLE
2016, 2017年のスポンサーロゴが表示されない

### ISSUE THREAD

**Issue by mshindo** [onicjapan/onicjapan.github.io#43]
2016: 日本電気株式会社、シスコシステムズ合同会社
2017: シスコシステムズ合同会社

のロゴが表示されない。

**Comment by canaan** [comment]
jpgファイル名が小文字/大文字に､yaml ファイルは小文字ですね。それぞれのブランチで修正したので､push しておきました，

**Comment by canaan** [comment]
また間違って､本家本元にPRを出してしまった。。。
ｺﾜｲので､PRを出すのを止めました。。。

**Comment by mshindo** [comment]
archives/2016, archives/2017 も直しておきました。

本家にPRが出てしまう件は簡単に治せそうにありませんが、一応 Issue をあげておくようにします。

本件は close とします。
