### ISSUE TITLE
開催趣旨文 for 2024 を掲載

### ISSUE THREAD

**Issue by mshindo** [onicjapan/onicjapan.github.io#70]
2024年の開催趣旨文を掲載する。

**Comment by mshindo** [comment]
大まかな手順は、

1. git clone
2. 2024 ブランチのチェックアウト (git checkout 2024)
3. 修正ブランチの作成 (git checkout -b 2024info)
4. index.md の修正
5. ローカルで確認
6. git add & git commit
7. ブランチ移動 (git checkout 2024)
8. 修正ブランチを 2024 ブランチにマージ (git merge 2024info)
9. git push origin 2024
10. https://www.onic.jp の確認

となります。

**Comment by tom-taniguchi** [comment]
変更完了しました。
一度、開催趣旨文のみ更新しています。続けてPOSTへのNEWS追加を行います。
![screencapture-onic-jp-2024-07-09-09_51_25](https://github.com/onicjapan/onicjapan.github.io/assets/140324151/aede4d03-9971-4fca-a613-46a9e61f6023)

**Comment by tom-taniguchi** [comment]
postのアップデート用のgit cloneが本日中に終わりそうに無いので、開催趣旨文の更新のcommit番号記載のみでcloseします。

commit [136f94b](https://github.com/chrisrhymes/bulma-clean-theme/commit/136f94ba9fb1283c5e1d98794cba79b1a5739fa2) "taniguchi_2024_info_update" 開催趣旨文の更新

**Comment by mshindo** [comment]
ブランチ切るたびに毎度 git clone する必要はないですよ。2024 の最新の状態からブランチを切ればいいだけです。谷口さんが  commit 136f94ba9fb1283c5e1d98794cba79b1a5739fa2 を 2024 ブランチに push した後、私が commit 468ee6b79c3ba549769e1f67e3e9f6ccc637d577 を push しているので、そのままでは谷口さんは 2024 ブランチに push できないと思います。その際には git pull して自分がローカルに持っている状態から先の GitHub 上の変更を取り入れてから push する必要があります。

**Comment by tom-taniguchi** [comment]
@mshindo 
またまた返信が遅くなり申し訳ありません。
git pull を行ってみたのですが、進藤さんのIの大文字化がローカルに反映されなかった（おそらく2024を再チェックアウトしてなかった？）ので、怖くなって新しくgit clone してしまいまいた。
ちょっと遅くなりましたが新しくpostをcommit[be54cd9](https://github.com/chrisrhymes/bulma-clean-theme/commit/be54cd9678e7931c21f84e6d93b40c62df129e75)しました。  
ご確認いただけますと幸いです。

**Comment by mshindo** [comment]
pull した後、2024 ブランチを checkout してなかったのなら、変更が見れなかったと思います。変更が入ったのは 2024 ブランチのみなので。

ともかく、正しく投稿はできましたので、この issue はクローズにしたいと思います。
