### ISSUE TITLE
BoF・本会議参加登録 for 2024 の掲載

### ISSUE THREAD

**Issue by mshindo** [onicjapan/onicjapan.github.io#72]

**Comment by tom-taniguchi** [comment]
以下で案内掲載完了しました。
BoF募集：commit [f0fe8ed](https://github.com/chrisrhymes/bulma-clean-theme/commit/f0fe8eddcd922579e08a165a3a69676e66cd1119) "create post of Bof announce"  

BoF／本会議参加登録：commit [4dbf15b](https://github.com/chrisrhymes/bulma-clean-theme/commit/4dbf15b3c11efdfd5fb746d11a944f535252bcbc) "create post of participation registration"
