### ISSUE TITLE
hashikenさんの所属アップデート

### ISSUE THREAD

**Issue by mshindo** [onicjapan/onicjapan.github.io#77]
実行委員メンバーとして記載されいている hashiken さんの所属を Ultra Red, Inc. -> Nozomi Networks へ変更

**Comment by hashiken-tech** [comment]
branch: 77-nozomi
で対応

**Comment by mshindo** [comment]
commit bbb8ab1c0c4bd9a740261ccc32365dc2a3884197 で fix。
