### ISSUE TITLE
BoF募集延長のPOST作成（9/3まで延長）

### ISSUE THREAD

**Issue by tom-taniguchi** [onicjapan/onicjapan.github.io#78]
BoFの募集締め切り（8/9金 → 9/3火）の変更をPOSTで案内する

**Comment by mshindo** [comment]
@tom-taniguchi さん、BoF期限延長はフォームの方で対応されて、Git Hub Pages の方の変更は無しですよね？　この issue はクローズしちゃってもいいでしょうか？

**Comment by tom-taniguchi** [comment]
本件は、POST作成は実施せずフォーム側での延長表記で対応したためクローズとする
