### ISSUE TITLE
TOPページに参加申し込みフォームへのリンクを追加

### ISSUE THREAD

**Issue by mshindo** [onicjapan/onicjapan.github.io#80]
今の状態だと、過去のPOSTをたどらないといけないので、ちょっと不便かなっと。by @hashiken-tech

**Comment by hashiken-tech** [comment]
プログラム概要と、参加申し込みフォームへのリンクを、TOPページに追加しました。

**Comment by hashiken-tech** [comment]
プログラム概要と、参加申し込みフォームへのリンクを、TOPページに追加しました。
